Desktop/cliente/src/main/java/com/cliente/cliente/controller/ClienteController.java
package com.cliente.cliente.controller;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.ocpsoft.rewrite.annotation.Join;
import org.ocpsoft.rewrite.el.ELBeanName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.cliente.cliente.dao.RepositorioCliente;
import com.cliente.cliente.to.Cliente;
import com.cliente.cliente.to.PessoaFisica;
import com.cliente.cliente.to.PessoaJuridica;
import com.cliente.enums.TipoPessoaEnum;

@Scope(value="session")
@Component(value = "clienteController")
@ELBeanName(value = "clienteController")
@Join(path = "/cliente", to = "/cliente/cadastro-cliente.jsf")
public class ClienteController {

	@Autowired
	private RepositorioCliente repositorio;
	
	private Cliente cliente;
	
	private boolean exibirCamposPF;
	private boolean exibirCamposPJ;

	public ClienteController() {
		exibirCamposPF=false;
		exibirCamposPJ=false;
		cliente = new Cliente();
	}
	
	
	public TipoPessoaEnum[] getTipoPessoa() {
		return TipoPessoaEnum.values();
	}

	public String salvar() {
		
		repositorio.save(cliente);
		cliente = new Cliente();
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Cliente Cadastrado", null);
		FacesContext.getCurrentInstance().addMessage("Teste teste", message);
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		return "/cliente/cliente-lista.xhtml?faces-redirect=true";
	}

	public Cliente getCliente() {
		return cliente;
	}


	public void renderizar() {  
		switch (cliente.getPessoa().getIdTipoPessoa()) {
		case 1:
			exibirCamposPJ = false;  
			exibirCamposPF = true;
			cliente = new Cliente(new PessoaFisica());
			break;
			
		case 2:
			exibirCamposPJ = true;  
			exibirCamposPF = false;
			cliente = new Cliente(new PessoaJuridica());
			break;

		default:
			exibirCamposPJ = false; 
			exibirCamposPF = false;
			cliente = new Cliente();
			break;
		}
        
    }  


	
	
	public boolean isExibirCamposPJ() {
		return exibirCamposPJ;
	}


	public void setExibirCamposPJ(boolean exibirCamposPJ) {
		this.exibirCamposPJ = exibirCamposPJ;
	}


	public boolean isExibirCamposPF() {
		return exibirCamposPF;
	}


	public void setExibirCamposPF(boolean exibirCamposPF) {
		this.exibirCamposPF = exibirCamposPF;
	}

	


	
	

}

Desktop/cliente/src/main/java/com/cliente/cliente/controller/ListaClienteController.java
package com.cliente.cliente.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.ocpsoft.rewrite.annotation.Join;
import org.ocpsoft.rewrite.annotation.RequestAction;
import org.ocpsoft.rewrite.el.ELBeanName;
import org.ocpsoft.rewrite.faces.annotation.Deferred;
import org.ocpsoft.rewrite.faces.annotation.IgnorePostback;
import org.primefaces.event.CellEditEvent;
import org.primefaces.event.RowEditEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.cliente.cliente.dao.RepositorioCliente;
import com.cliente.cliente.to.Cliente;
import com.cliente.enums.TipoPessoaEnum;

@Scope(value="session")
@Component(value = "listaClientes")
@ELBeanName(value = "listaClientes")
@Join(path = "/", to = "/cliente/cliente-lista.jsf")
public class ListaClienteController {

	@Autowired
	private RepositorioCliente repositorio;

	private List<Cliente> clientes;

	private Cliente clienteSelecionado;



	public ListaClienteController() {
		clienteSelecionado = new Cliente();
	}

	@Deferred
	@RequestAction
	@IgnorePostback
	public void loadData() {
		clientes = repositorio.findAll();
		return;
	}

	public List<Cliente> getClientes() {
		return clientes;
	}

	public String deletarCliente() {

		repositorio.deleteById(clienteSelecionado.getIdCliente());
		loadData();
		getClientes();
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Cliente Excluído, pressione F5", null);
		FacesContext.getCurrentInstance().addMessage("Cliente Excluído", message);
		return null;
	}

	public Cliente getClienteSelecionado() {
		return clienteSelecionado;
	}

	public void setClienteSelecionado(Cliente clienteSelecionado) {
		this.clienteSelecionado = clienteSelecionado;
	}

	// Metodos para edição na tabela
	public void onRowEdit(RowEditEvent event) {
		Cliente clienteEditado = (Cliente) event.getObject();
		repositorio.save(clienteEditado);
		FacesMessage msg = new FacesMessage("Edição de cliente ", "O cliente "+clienteEditado.getPessoa().getNome()+" foi editado com sucesso!");
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void onRowCancel(RowEditEvent event) {
		Cliente clienteEditado = (Cliente) event.getObject();
		FacesMessage msg = new FacesMessage("Edição Cancelada",  "O cliente "+clienteEditado.getPessoa().getNome()+" não editado!");
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void onCellEdit(CellEditEvent event) {
		Object oldValue = event.getOldValue();
		Object newValue = event.getNewValue();

		if (newValue != null && !newValue.equals(oldValue)) {
			FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Célula Editada",
					"Antes: " + oldValue + ", Agora:" + newValue);
			FacesContext.getCurrentInstance().addMessage(null, msg);
		}
	}
	
	

}

Desktop/cliente/src/main/webapp/cliente/cadastro-cliente.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<ui:composition template="../layout.xhtml">

	<ui:define name="content">
		<h:form id="clienteForm">
			<p:panel header="Cadastro de Cliente">
				<h:panelGrid columns="1" id="grid">


					<p:selectOneMenu
						value="#{clienteController.cliente.pessoa.idTipoPessoa}"
						required="true">
						<f:selectItem itemLabel="Selecione..." itemValue=""
							noSelectionOption="true" />

						<f:selectItems value="#{clienteController.tipoPessoa}"
							itemValue="#{tipo.valor}" var="tipo" itemLabel="#{tipo.chave}" />

						<p:ajax listener="#{clienteController.renderizar}" process="@this"
							update="clienteForm:parentBlock" />
					</p:selectOneMenu>
				</h:panelGrid>

				<h:panelGrid id="parentBlock" columns="1">
					<p:outputLabel for="nome" value="Nome:"
						rendered="#{clienteController.exibirCamposPJ || clienteController.exibirCamposPF}" />
					<p:inputText id="nome"
						value="#{clienteController.cliente.pessoa.nome}"
						rendered="#{clienteController.exibirCamposPJ || clienteController.exibirCamposPF}" />

					<p:outputLabel for="CPF" value="CPF: "
						rendered="#{clienteController.exibirCamposPF}" />
					<p:inputMask mask="999.999.999-99" id="CPF"
						value="#{clienteController.cliente.pessoa.cpf}"
						rendered="#{clienteController.exibirCamposPF}">

					</p:inputMask>

					<p:outputLabel for="CNPJ" value="CNPJ: "
						rendered="#{clienteController.exibirCamposPJ}" />
					<p:inputMask mask="99.999.999/9999-99" id="CNPJ"
						value="#{clienteController.cliente.pessoa.cnpj}"
						rendered="#{clienteController.exibirCamposPJ}" />


					<p:outputLabel for="ativo" value="Ativo: "
						rendered="#{clienteController.exibirCamposPJ || clienteController.exibirCamposPF}" />
					<p:selectBooleanCheckbox id="ativo"
						value="#{clienteController.cliente.ativo}"
						rendered="#{clienteController.exibirCamposPJ || clienteController.exibirCamposPF}" />


				</h:panelGrid>



				<h:commandButton value="Salvar" action="#{clienteController.salvar}">



				</h:commandButton>
				<h:panelGrid id="criticas" columns="1">

					<h:message for="CPF" style="color:red;margin:8px;" />
					<h:message for="CNPJ" style="color:red;margin:8px;" />
					<h:message for="nome" style="color:red;margin:8px;" />
				</h:panelGrid>



			</p:panel>
		</h:form>
	</ui:define>

</ui:composition>
</html>

Desktop/cliente/src/main/webapp/cliente/cliente-lista.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<ui:composition template="../layout.xhtml">

	<ui:define name="content">
		<h:form id="form">

			<p:growl id="mensagem" showDetail="true" />

			<p:panel id="painel" header="Lista de Clientes">
				<p:dataTable id="tabCliente" var="cliente"
					value="#{listaClientes.clientes}" rows="10" paginator="true"
					paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					emptyMessage="Nenhum registro encontrado!"
					filteredValue="#{listaClientes.clientes}" editable="true">

					<p:ajax event="rowEdit" listener="#{listaClientes.onRowEdit}"
						update=":form:mensagem" />
					<p:ajax event="rowEditCancel"
						listener="#{listaClientes.onRowCancel}" update=":form:mensagem" />

					<p:column headerText="# Id" sortBy="#{cliente.idCliente}"
						filterMatchMode="contains">
						<h:outputText value="#{cliente.idCliente}" />
					</p:column>

					<p:column headerText="Nome" sortBy="#{cliente.pessoa.nome}">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{cliente.pessoa.nome}" />
							</f:facet>
							<f:facet name="input">
								<p:inputText value="#{cliente.pessoa.nome}" />
							</f:facet>
						</p:cellEditor>

					</p:column>

					<p:column headerText="Ativo" sortBy="#{cliente.ativo}">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{cliente.ativo?'Sim':'Não'}" />
							</f:facet>
							<f:facet name="input">
								<p:selectBooleanCheckbox value="#{cliente.ativo}" />
							</f:facet>
						</p:cellEditor>

					</p:column>


					<p:column headerText="Tipo Pessoa"
						sortBy="#{cliente.pessoa.idTipoPessoa}">

						<h:outputText
							value="#{cliente.pessoa.idTipoPessoa eq 1? 'Física':'Jurídica'}" />



					</p:column>


					<p:column headerText="CPF/CNPJ">

						<h:outputText
							value="#{cliente.pessoa.idTipoPessoa eq 1? cliente.pessoa.cpf:cliente.pessoa.cnpj}" />



					</p:column>



					<p:column style="width:32px">
						<p:rowEditor />
					</p:column>



					<p:column>

						<p:commandLink class="ui-icon ui-icon-trash" id="detelar"
							onclick="PF('confirmacaoExclusao').show()">

							<f:setPropertyActionListener
								target="#{listaClientes.clienteSelecionado}" value="#{cliente}" />


						</p:commandLink>


					</p:column>






				</p:dataTable>
			</p:panel>



			<p:confirmDialog id="confirmacaoExclusao"
				widgetVar="confirmacaoExclusao" message="Deseja realmente excluir?"
				header="Exclusão de Cliente" severity="alert" appendToBody="true">
				<h:messages />

				<p:commandButton value="Sim" styleClass="ui-confirmdialog-yes"
					icon="ui-icon-check" onclick="PF('confirmacaoExclusao').hide()"
					action="#{listaClientes.deletarCliente}"
					update="form:painel form:tabCliente form:mensagem" />
				<p:commandButton value="Não" styleClass="ui-confirmdialog-no"
					icon="ui-icon-close" onclick="PF('confirmacaoExclusao').hide()" />

			</p:confirmDialog>


		</h:form>
	</ui:define>

</ui:composition>
</html>

Desktop/cliente/src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:p="http://primefaces.org/ui">
<f:view>
<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title><ui:insert name="title">Manutenção de Clientes</ui:insert></title>
</h:head>
<h:body>
	<div class="ui-g">
		<div class="ui-g-12">
			<p:growl for="errors" showDetail="true" autoUpdate="true"/>
		</div>
		<div class="ui-g-12">
			<p:toolbar>
				<f:facet name="left">
					<p:button href="/" value="Lista de Clientes" />
					<p:button href="/cliente" value="Cadastrar Cliente" />
				</f:facet>
			</p:toolbar>
		</div>
		<div class="ui-g-12">
			<ui:insert name="content">Default content</ui:insert>
		</div>
	</div>
</h:body>
</f:view>
</html>